#!/bin/bash

# Run this script on the new server.

# Things to do before running this script:
#
# The following files contain the PostgreSQL password:
# /home/whatever/greenlight/docker-compose.yml
# /home/whatever/greenlight/.env                
# It was generated by bbb-install.sh and is also persisted in the PostgreSQL database files.
# The easiest way is changing those files to contain the old password.



echo "=== Please ensure BBB and Greenlight are stopped on the source server!"
read -p "Press enter to continue."


# On the final run, --delete should probably be used; for test runs it's probably safer without --delete
RSYNC="rsync -a -x -AHX -S --numeric-ids --delete-after -v -P --stats -h -y "
#RSYNC="rsync -a -x -AHX -S --numeric-ids -v -P --stats -h -y"

# Where the old BBB server is located
SRC="root@bbb4.avm-konferenz.de"
# Hostname of the new server
DST_HOSTNAME="bbb5.avm-konferenz.de"

# Where greenlight was installed to by bbb-install.sh on this server
GREENLIGHT="/home/marc/greenlight"
# Where greenlight was installed to by bbb-install.sh on the old server
SRC_GREENLIGHT="/home/marc/greenlight"


# Stop BBB
bbb-conf --stop
# Also stop Greenlight, as we are syncing the PostgreSQL database
docker-compose -f $GREENLIGHT/docker-compose.yml down

# Sync Greenlight PostgreSQL database
$RSYNC $SRC:$SRC_GREENLIGHT/db/ $GREENLIGHT/db/
# Sync recordings
$RSYNC $SRC:/var/bigbluebutton/ /var/bigbluebutton/
# Sync whatever is in the freeswitch directory, if anything
$RSYNC $SRC:/var/freeswitch/meetings/ /var/freeswitch/meetings/
# NOTE: that's only something on my system; just remove it.
$RSYNC $SRC:/docker-compose/ /docker-compose/ 

# Fix the hostname in the recordings
bbb-conf --setip $DST_HOSTNAME

# Start up Greenlight
docker-compose -f $GREENLIGHT/docker-compose.yml up -d
# Start up BBB
bbb-conf --start

# Run checks
echo "=== I'm waiting for some seconds to give services some time to spin up..."
sleep 30
bbb-conf --check
# Print status
bbb-conf --status
