#!/bin/bash

# Run this script on the new server.

# Things to do before running this script:
#
# The following files contain the PostgreSQL password:
# /home/whatever/greenlight/docker-compose.yml
# /home/whatever/greenlight/.env                
# It was generated by bbb-install.sh and is also persisted in the PostgreSQL database files.
# The easiest way is changing those files to contain the old password.
#
# Do not change any other secrets!
#
# Older versions of Greenlight docker-compose.yml used PostgreSQL 9 while newer use 13.2.
# Unfortunately, the database files are not binary compatible.
# Easiest solution is to just use the version on your source server.
#
# As this scripts calls a dozen times ssh, you probably want to use a key and manage it via ssh-agent.
# $ sudo -s
# $ eval "$(ssh-agent -s)"
# $ ssh-add ~user/.ssh/id_ecdsa

echo "= Please ensure you are root and have your ssh key loaded into the ssh-agent:"
echo "$ sudo -s"
echo "$ eval \"$(ssh-agent -s)\""
echo "$ ssh-add ~user/.ssh/id_ecdsa"

echo "= Please ensure BBB and Greenlight are stopped on the source server!"
read -p "Press enter to continue."

# Configuration

# On the final run, --delete should probably be used; for test runs it's probably safer without --delete
#RSYNC="rsync -a -x -AHX -S --numeric-ids -v -P --stats -h -y --delete-after"
RSYNC="rsync -a -x -AHX -S --numeric-ids -v -P --stats -h -y"

# Where the old BBB server is located
SRC="root@bbb4.avm-konferenz.de"
# Hostname of the new server
DST_HOSTNAME="bbb5.avm-konferenz.de"

# Where greenlight was installed to by bbb-install.sh on this server
GREENLIGHT="/root/greenlight"
# Where greenlight was installed to by bbb-install.sh on the old server
SRC_GREENLIGHT="/home/marc/greenlight"

function stop_services() {
    echo "= Stopping services..."

    # Stop BBB
    bbb-conf --stop

    # Also stop Greenlight, as we are syncing the PostgreSQL database
    docker-compose -f $GREENLIGHT/docker-compose.yml down
}

function rsync_all() {
    echo "= Synchronizing data..."

    # Sync Greenlight PostgreSQL database
    $RSYNC $SRC:$SRC_GREENLIGHT/db/ $GREENLIGHT/db/

    # Sync recordings
    $RSYNC $SRC:/var/bigbluebutton/ /var/bigbluebutton/

    # Sync whatever is in the freeswitch directory, if anything
    $RSYNC $SRC:/var/freeswitch/meetings/ /var/freeswitch/meetings/

    # NOTE: that's only something on my system; just remove it.
    $RSYNC $SRC:/docker-compose/ /docker-compose/ 
}

function fix_things() {
    echo "= Fixing things after synchronization..."

    # Fix the hostname in the recordings
    bbb-conf --setip $DST_HOSTNAME
}

function start_services() {
    echo "= Starting services..."

    # Start up Greenlight
    docker-compose -f $GREENLIGHT/docker-compose.yml up -d

    # Start up BBB
    bbb-conf --start
}

function run_checks() {
    echo "= Running checks..."

    SLEEP_DURATION=30
    echo "=== I'm waiting for $SLEEP_DURATION seconds to give services some time to spin up..."
    sleep $SLEEP_DURATION

    # Run checks
    bbb-conf --check

    # Print status
    bbb-conf --status
}

stop_services
rsync_all
fix_things
start_services
run_checks
